export const CLEAR_SESSION = "CLEAR_SESSION";
export const SET_SESSION = "SET_SESSION";
export const SETTING_SESSION = "SETTING_SESSION";
export const COMPLETE_SESSION_SETTING = "COMPLETE_SESSION_SETTING";
export const SET_UNITY_READY = "SET_UNITY_READY";
export const SET_WAITING_FOR_UNITY = "SET_WAITING_FOR_UNITY";

// Profile
export const SET_LOADING_PROFILE = "SET_LOADING_PROFILE";
export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
